Models/Item.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace TabApp.Models
{
    public class Item
    {
        public int ID { get; set; }

        [Display(Name = "Serial number")]
        [StringLength(100, MinimumLength = 3)]
        [Required]
        public String SerialNumber { get; set; }


        [StringLength(100, MinimumLength = 3)]
        [Required]
        public String Description { get; set; }

        public Person Person { get; set; }
        
        public ICollection<Repair> Repair { get; set; }
    }

}

Controllers/ItemController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using TabApp.Models;


namespace TabApp.Controllers
{
    [Authorize]
    public class ItemController : Controller
    {
        private readonly dbContext _context;

        public ItemController(dbContext context)
        {
            _context = context;
        }

        // GET: Item
        public async Task<IActionResult> Index()
        {
            return View(await _context.Item.Include("Person").ToListAsync());
        }

        public async Task<IActionResult> SelectOwner(string Description, string SerialNumber, string NameFilter, string SurnameFilter)
        {
            ViewBag.Description = Description;
            ViewBag.SerialNumber = SerialNumber;
            ViewBag.NameFilter = NameFilter;
            ViewBag.SurnameFilter = SurnameFilter;

            IQueryable<Person> unfiltered_users = _context.Person;

            if (!String.IsNullOrEmpty(NameFilter))
            {
                unfiltered_users = unfiltered_users.Where(u => u.Name.Contains(NameFilter));
            }
            if (!String.IsNullOrEmpty(SurnameFilter))
            {
                unfiltered_users = unfiltered_users.Where(u => u.Surname.Contains(SurnameFilter));
            }
            unfiltered_users = unfiltered_users.OrderBy(m => m.Surname);

            var users = await unfiltered_users.ToListAsync();

            return View(users);

        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> AddItemWithPerson(string Description, string SerialNumber, int PersonID)
        {
            Item item = new Item
            {
                SerialNumber = SerialNumber,
                Description = Description
            };

            var person = _context.Person.Where(p => p.ID == PersonID).FirstAsync();
            
            if (person.Result == null)
                return RedirectToAction(nameof(Index));

            item.Person = person.Result;
            _context.Add(item);
            await _context.SaveChangesAsync();

            return RedirectToAction(nameof(Index));
        }
        
        public async Task<IActionResult> RepairList(int? itemID)
        {
            if (itemID == null)
            {
                return NotFound();
            }

            var item = await _context.Item
            .Include(i => i.Repair)
            .FirstOrDefaultAsync(it => it.ID == itemID);

            var repairs  = new List<Repair>();
            foreach(var repair in item.Repair)
            {
                var tmpService =  await _context.Repair.Include(r => r.PickupCode).Include(r => r.RepairStatus).FirstOrDefaultAsync(r => r.ID == repair.ID);
                repairs.Add(tmpService);
            }

            return View(repairs);
        }
        public IActionResult AddNewPerson(string Description, string SerialNumber)
        {
            ViewBag.Description = Description;
            ViewBag.SerialNumber = SerialNumber;
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> AddNewPerson(string Description,string SerialNumber,[Bind("ID,Role,Name,Surname,Address,Email,PhoneNumber")] Person person)
        {
            Item item = new Item();

            item.SerialNumber=SerialNumber;
            item.Description = Description;

            if (ModelState.IsValid)
            {
                _context.Add(person);
                await _context.SaveChangesAsync();
            }

            item.Person = person;
            _context.Add(item);
            await _context.SaveChangesAsync();

            return RedirectToAction(nameof(Index));
        }

        // GET: Item/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var item = await _context.Item
                .FirstOrDefaultAsync(m => m.ID == id);
            if (item == null)
            {
                return NotFound();
            }

            return View(item);
        }

        // GET: Item/Create
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("ID,SerialNumber,Description")] Item item)
        {
            if (ModelState.IsValid)
            {
                _context.Add(item);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(item);
        }

        // GET: Item/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var item = await _context.Item.FindAsync(id);
            if (item == null)
            {
                return NotFound();
            }
            return View(item);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("ID,SerialNumber,Description")] Item item)
        {
            if (id != item.ID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(item);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ItemExists(item.ID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(item);
        }

        // GET: Item/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var item = await _context.Item
                .FirstOrDefaultAsync(m => m.ID == id);
            if (item == null)
            {
                return NotFound();
            }

            return View(item);
        }

        // POST: Item/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var item = await _context.Item.FindAsync(id);
            _context.Repair.RemoveRange(_context.Repair.Where(x => x.Item == item));
            _context.Item.Remove(item);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool ItemExists(int id)
        {
            return _context.Item.Any(e => e.ID == id);
        }
    }
}

Controllers/RepairController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using TabApp.Models;
using TabApp.Enums;
using Microsoft.AspNetCore.Authorization;

namespace TabApp.Controllers
{
    [Authorize]
    public class RepairController : Controller
    {
        private readonly dbContext _context;

        public RepairController(dbContext context)
        {
            _context = context;
        }

        // GET: Repair
        public async Task<IActionResult> Index()
        {
            var dbContext = _context.Repair.Include(r => r.Item).Include(r => r.RepairStatus).Include(r => r.PickupCode);
            return View(await dbContext.ToListAsync());
        }

        // GET: Repair/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var repair = await _context.Repair
                .Include(r => r.Item)
                .Include(r => r.RepairStatus)
                .Include(r => r.PickupCode)
                .FirstOrDefaultAsync(m => m.ID == id);
    
            if (repair == null)
            {
                return NotFound();
            }

            return View(repair);
        }
        public IActionResult Add()
        {
            return View();
        }

        // GET: Repair/Create/itemId
        public async Task<IActionResult> Create(int? itemID)
        {
            if (itemID != null)
            {
                var item = await _context.Item.FindAsync(itemID);
                if (item == null)
                {
                    return NotFound();
                }
                ViewBag.ItemID = itemID;
                ViewBag.ItemSerialNumber = item.SerialNumber;
                ViewBag.ItemDescription = item.Description; 
            }

            return View();
        }



        public string Status { get; set; }

        // POST: Repair/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(int? itemID, [Bind("AdmissionDate,Cost,Warranty")] Repair repair, 
        [Bind("SerialNumber,Description")] Item item)
        {
            if (ModelState.IsValid)
            {
                if(itemID != null)
                {
                    var existingItem = await _context.Item.FindAsync(itemID);
                    if (existingItem == null)
                    {
                        return NotFound();
                    }
                    repair.Item = existingItem;
                }  
                else
                {
                    _context.Add(item);
                    await _context.SaveChangesAsync();
                    repair.Item = item;
                }

                var repairStatus = await _context.RepairStatus.FindAsync(1);
                repair.RepairStatus = repairStatus;


                _context.Add(repair);
                await _context.SaveChangesAsync();

                var pickupCode = await _context.PickupCodes.FindAsync(repair.ID);
                repair.PickupCode = pickupCode;
                await _context.SaveChangesAsync();

                return RedirectToAction(nameof(Index));
            }
            return View(repair);
        }

        // GET: Repair/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var repair = await _context.Repair
                .Include(r => r.RepairStatus)
                .FirstOrDefaultAsync(m => m.ID == id);

            if (repair == null)
            {
                return NotFound();
            }
            ViewData["RepairStatus"] = new SelectList(_context.RepairStatus, "ID", "Status", repair.RepairStatus.ID);
            return View(repair);
        }

        // POST: Repair/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, int repairStatusID, [Bind("ID,AdmissionDate,Warranty")] Repair repair)
        {
            if (id != repair.ID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    var oldRepair = await _context.Repair
                    .Include(r => r.Item)
                    .Include(r => r.PickupCode)
                    .Include(r => r.Service)
                    .FirstOrDefaultAsync(m => m.ID == id);
                    
                    var repairStatus = await _context.RepairStatus.FindAsync(repairStatusID);

                    oldRepair.AdmissionDate = repair.AdmissionDate;
                    oldRepair.Warranty = repair.Warranty;
                    oldRepair.RepairStatus = repairStatus;

                    if(repairStatus.Status == RepairStatuses.Ready)
                    {
                        oldRepair.IssueDate = DateTime.Today;
                        if(oldRepair.Service != null)
                        {
                            oldRepair.Cost = 0;
                            foreach(var service in oldRepair.Service)
                            {
                                var tmpService =  await _context.Service.Include(s => s.PriceList).FirstOrDefaultAsync(s => s.ID == service.ID); 
                                if(tmpService != null) 
                                    oldRepair.Cost += tmpService.PriceList.Price;

                                if(tmpService.PartsCost != null) 
                                   oldRepair.Cost += tmpService.PartsCost;                       
                            }
                        }
                        
                    }

                    _context.Update(oldRepair);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!RepairExists(repair.ID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["RepairStatus"] = new SelectList(_context.RepairStatus, "ID", "Status", repair.RepairStatus.ID);
            //ViewData["ItemID"] = new SelectList(_context.Item, "ID", "Description", repair.ItemID);
            return View(repair);
        }

        // GET: Repair/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var repair = await _context.Repair
                .Include(r => r.Item)
                .FirstOrDefaultAsync(m => m.ID == id);
            if (repair == null)
            {
                return NotFound();
            }

            return View(repair);
        }

        // POST: Repair/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var repair = await _context.Repair
            .Include("Invoice")
            .FirstOrDefaultAsync(m => m.ID == id);
            _context.Service.RemoveRange(_context.Service.Where(x => x.Repair == repair));
            _context.Invoice.Remove(repair.Invoice);
            _context.Repair.Remove(repair);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool RepairExists(int id)
        {
            return _context.Repair.Any(e => e.ID == id);
        }
    }
}

Views/Item/AddNewPerson.cshtml
@model TabApp.Models.Person

@{
    ViewData["Title"] = "Add person with item";
}

<h2>Add person with item</h2>

<div class="row">
    <div class="col-md-6">

        <h5>Person data</h5>
        <form asp-action="AddNewPerson">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Surname" class="control-label"></label>
                <input asp-for="Surname" class="form-control" />
                <span asp-validation-for="Surname" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Address" class="control-label"></label>
                <input asp-for="Address" class="form-control" />
                <span asp-validation-for="Address" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Email" class="control-label"></label>
                <input asp-for="Email" class="form-control" />
                <span asp-validation-for="Email" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PhoneNumber" class="control-label"></label>
                <input asp-for="PhoneNumber" class="form-control" />
                <span asp-validation-for="PhoneNumber" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input asp-for="Role" type="hidden" value="User" class="form-control">
            </div>

            <h5>Item data</h5>
            <div class="form-group">
                <label aclass="control-label">Serial number</label>
                <input value="@ViewBag.SerialNumber" name="SerialNumber" id="SerialNumber" class="form-control" readonly>
            </div>
            <div class="form-group">
                <label class="control-label">Description</label>
                <input value="@ViewBag.Description" name="Description" id="Description" class="form-control" readonly>
            </div>

            <div class="form-group">
                <input asp-for="Role" type="hidden" value="User" class="form-control">
            </div>
            <div class="form-group">
                <input type="submit" value="Create item and person" class="btn btn-outline-success" style="margin-right:10px;"/>
                <a class="btn btn-outline-danger" asp-action="Index">Back to List</a>
            </div>
        </form>
    </div>
</div>

<div>
    
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Item/Create.cshtml
@model TabApp.Models.Item

@{
    ViewData["Title"] = "Add new item";
}

<h2>Add new item</h2>
<div class="row">
    <div class="col-md-6">
        <form>
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="SerialNumber" class="control-label"></label>
                <input asp-for="SerialNumber" class="form-control" />
                <span asp-validation-for="SerialNumber" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input asp-action="AddNewPerson" type="submit" value="Add with new person" class="btn btn-outline-primary" />
                <input asp-action="SelectOwner" type="submit" value="Add to existing person" class="btn btn-outline-primary" />
                <a asp-action="Index" class="btn btn-outline-danger">Back to List</a>
            </div>
        </form>
    </div>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Item/Delete.cshtml
@model TabApp.Models.Item

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Item</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.SerialNumber)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.SerialNumber)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Description)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Description)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="ID" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

Views/Item/Details.cshtml
@model TabApp.Models.Item

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Item</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.SerialNumber)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.SerialNumber)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Description)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Description)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.ID">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

Views/Item/Edit.cshtml
@model TabApp.Models.Item

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Item</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="ID" />
            <div class="form-group">
                <label asp-for="SerialNumber" class="control-label"></label>
                <input asp-for="SerialNumber" class="form-control" />
                <span asp-validation-for="SerialNumber" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Item/Index.cshtml
@model IEnumerable<TabApp.Models.Item>

@{
    ViewData["Title"] = "Items";
}

<h2>Items</h2>

<p>
    <a asp-action="Create" class="btn btn-outline-primary">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.SerialNumber)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Description)
            </th>
            <th>
                User
            </th>
            <th>
            </th>
            </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.SerialNumber)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Description)
            </td>
            <td>
                <a asp-action="Details" asp-controller="Person" asp-route-id="@item.Person.ID">@Html.DisplayFor(modelItem => item.Person.Name) @Html.DisplayFor(modelItem => item.Person.Surname)</a>
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.ID">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.ID">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.ID">Delete</a> |
                <a asp-action="RepairList" asp-route-itemID="@item.ID">Repair List</a> |
                <a asp-controller="Repair" asp-action="Create" asp-route-itemID="@item.ID">Add repair</a>
            </td>
        </tr>
}
    </tbody>
</table>

Views/Item/RepairList.cshtml
@model IEnumerable<TabApp.Models.Repair>

@{
    ViewData["Title"] = "RepairList";
}

<h2>RepairList</h2>

<table class="table">
    <thead>
        <tr>
            <th>
                Admission Date
            </th>
            <th>
                Status
            </th>
            <th>
                Pickup Code
            </th>
            
        </tr>
    </thead>
    <tbody>
@foreach (var repair in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => repair.AdmissionDate)
            </td>
                        <td>
                @Html.DisplayFor(modelItem => repair.RepairStatus.Status)
            </td>
                        <td>
                @Html.DisplayFor(modelItem => repair.PickupCode.Value)
            </td>

            <td>
                <a asp-controller="Repair" asp-action="Edit" asp-route-id="@repair.ID">Edit</a> |
                <a asp-controller="Repair" asp-action="Details" asp-route-id="@repair.ID">Details</a> |
                <a asp-controller="Repair" asp-action="Delete" asp-route-id="@repair.ID">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>

Views/Item/SelectOwner.cshtml
@model IEnumerable<TabApp.Models.Person>

    @{
    ViewData["Title"] = "Persons";
    }

    <h2>Chose existing person</h2>


    <div class="container">
        <h5>Item data</h5>
        <form asp-controller="Item" asp-action="SelectOwner">

            <div class="col-md-4">
                <label class="control-label">Serial number</label>
                <input class="form-control" name="SerialNumber" value="@ViewBag.SerialNumber" readonly>
                <label class="control-label">Descriptrion</label>
                <input class="form-control" name="Description" value="@ViewBag.Description" readonly>
            </div>

            <!-- <p>
                <a asp-action="Create" class="btn btn-outline-primary my-2 my-sm-0" style="padding-right:15px;">Send message</a>
                <a asp-action="SendToWorker" class="btn btn-outline-primary my-2 my-sm-0" style="padding-right:15px;">Contact Support</a>
                <a asp-action="SendBox" class="btn btn-outline-success my-2 my-sm-0">Sent by me</a>
            </p>-->
            <br />

            <h5>Persons list</h5>
            <table class="table">
                <thead>
                    <tr>
                        <th>
                            Name
                        </th>
                        <th>
                            Surname
                        </th>
                        <th>
                            Address
                        </th>
                        <th>
                            Email
                        </th>
                        <th>
                            Phone number
                        </th>
                        <th>

                        </th>
                    </tr>
                </thead>

                <tbody>
                    <tr>

                        <th>
                            <input type=text name="NameFilter" value="@ViewBag.NameFilter">
                        </th>
                        <th>
                            <input type=text name="SurnameFilter" value="@ViewBag.SurnameFilter">
                        </th>
                        <th>
                        </th>
                        <th>
                        </th>
                        <th>
                        </th>
                        <th>
                            <button type="submit" class="btn btn-outline-primary my-2 my-sm-0"> Filter </button>

                        </th>
                    </tr>
        </form>

        @foreach (var person in Model)
        {
        <tr>
            <td>
                @Html.DisplayFor(modelPerson => person.Name)
            </td>
            <td>
                @Html.DisplayFor(modelPerson => person.Surname)

            </td>
            <td>
                @Html.DisplayFor(modelPerson => person.Address)
            </td>
            <td>
                @Html.DisplayFor(modelPerson => person.Email)

            </td>
            <td>
                @Html.DisplayFor(modelPerson => person.PhoneNumber)
            </td>
            <td>
                <form asp-controller="Item" asp-action="AddItemWithPerson">
                    <input type=hidden name="SerialNumber" value="@ViewBag.SerialNumber">
                    <input type=hidden name="Description" value="@ViewBag.Description">
                    <input type=hidden name="PersonID" value="@person.ID">
                    <button type="submit" class="btn btn-outline-success my-2 my-sm-0"> Choose </button>
                </form>
            </td>
        </tr>
        }
        </tbody>
        </table>

    </div>

Views/Item/UsersItems.cshtml
@model IEnumerable<TabApp.Models.Item>

    @{
    ViewData["Title"] = "Items";
    }

    <h1>Items</h1>

    <p>
        <a asp-action="Create">Create New</a>
    </p>
    <table class="table">
        <thead>
            <tr>
                <th>
                    @Html.DisplayNameFor(model => model.SerialNumber)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Description)
                </th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model) {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.SerialNumber)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Description)
                </td>
            </tr>
            }
        </tbody>
    </table>