Controllers/UserRepairsController.cs
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using TabApp.Models;


namespace TabApp.Controllers
{
    public class UserRepairsController : Controller
    {
        private readonly dbContext _context;

        public UserRepairsController(dbContext context)
        {
            _context = context;
        }

        public async Task<IActionResult> Index()
        {   
            var currentUserID = await _context.Person.Where(u => u.LoginCredentials.UserName == User.Identity.Name).Select(p => p.ID).FirstAsync();
            /////////

            var items = _context.Item.Include(i => i.Repair).Where(item=>item.Person.ID == currentUserID).ToListAsync();

            var repairs  = new List<Repair>();
            foreach(var item in items.Result)
            {
            foreach(var repair in item.Repair)
            {
                var tmpRepair =  await _context.Repair.Include(r => r.PickupCode).Include(r => r.RepairStatus).FirstOrDefaultAsync(r => r.ID == repair.ID);
                repairs.Add(tmpRepair);
            }
            }

            return View(repairs);
        }
        public async Task<IActionResult> UserServices(int? repairID)
        {
            if (repairID == null)
            {
                return NotFound();
            }
            
            var repair = await _context.Repair
            .Include(r => r.Service)
            .Include(r => r.PickupCode)
            .FirstOrDefaultAsync(m => m.ID == repairID);       

            var services  = new List<Service>();
            foreach(var service in repair.Service)
            {
                var tmpService =  await _context.Service.Include(s => s.PriceList).FirstOrDefaultAsync(s => s.ID == service.ID);  
                services.Add(tmpService);
            }
            ViewBag.PickupCode = repair.PickupCode.Value;
            ViewBag.RepairID = repairID;
            return View(services);
        }
        
        public async Task<IActionResult> Details(int? id, int? repairID)
        {
            if (id == null || repairID == null)
            {
                return NotFound();
            }

            var service = await _context.Service
                .Include(s => s.PriceList)
                .FirstOrDefaultAsync(m => m.ID == id);
            if (service == null)
            {
                return NotFound();
            }
            ViewBag.RepairID = repairID;
            return View(service);
        }
        private bool ServiceExists(int id)
        {
            return _context.Service.Any(e => e.ID == id);
        }
    }
}

Views/UserRepairs/Details.cshtml
@model TabApp.Models.Service

@{
    ViewData["Title"] = "Details";
}

<h1>Details </h1>

<div>
    <h4>Service</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.WarrantyDate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.WarrantyDate)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.PartsCost)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.PartsCost)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.PriceList.Price)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.PriceList.Price) zł
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.PriceList.Description)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.PriceList.Description)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="UserServices" asp-route-repairID="@ViewBag.RepairID" class="btn btn-outline-danger my-2 my-sm-0">Back</a>
</div>

Views/UserRepairs/Index.cshtml
@model IEnumerable<TabApp.Models.Repair>

@{
    ViewData["Title"] = "Index";
}

<h2>Repairs</h2>

<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.AdmissionDate)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.IssueDate)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Cost)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.RepairStatus)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.PickupCode)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Item)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.AdmissionDate)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.IssueDate)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Cost)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.RepairStatus.Status)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.PickupCode.Value)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Item.Description)
            </td>
            <td>
                <a asp-action="UserServices" asp-route-repairID="@item.ID">Show services</a> 
            </td>
        </tr>
}
    </tbody>
</table>

Views/UserRepairs/UserServices.cshtml
@model IEnumerable<TabApp.Models.Service>

@{
    ViewData["Title"] = "Index";
}

<h1>Services for repair @ViewBag.PickupCode </h1>

<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.WarrantyDate)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.PriceList.Price)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.PriceList.Description)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.WarrantyDate)
            </td>
            <td>
                @{
                    int fullPrice;
                    if(item.PartsCost != null)
                    {
                        fullPrice = item.PriceList.Price + (int)item.PartsCost;
                    }
                    else
                    {
                        fullPrice = item.PriceList.Price;
                    }
                    @Html.DisplayFor(modelItem => fullPrice)
                } zł
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.PriceList.Description)

            </td>
            <td>
                <a asp-action="Details" asp-route-id="@item.ID" asp-route-repairID="@ViewBag.RepairID">Details</a> 
            </td>
        </tr>
}
    </tbody>
</table>

<div>
    <a asp-controller="UserRepairs" asp-action="Index" class="btn btn-outline-danger my-2 my-sm-0"> Back </a>
</div>	