Models/Repair.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace TabApp.Models
{
    public class Repair
    {
        public int ID { get; set; }

        [DataType(DataType.Date)]
        public DateTime AdmissionDate { get; set; }

        [DataType(DataType.Date)]
        public DateTime? IssueDate { get; set; }

        [DataType(DataType.Currency)]
        public int? Cost { get; set; }

        public bool Warranty {get; set;}      

        public Item Item { get; set; }

        public Invoice Invoice { get; set; }

        public virtual RepairStatus RepairStatus { get; set; }
       
        [ForeignKey("PickupCodeID")]
        public virtual PickupCode PickupCode { get; set; }

        public ICollection<Service> Service { get; set; }

    }

}

Controllers/ItemController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using TabApp.Models;


namespace TabApp.Controllers
{
    [Authorize]
    public class ItemController : Controller
    {
        private readonly dbContext _context;

        public ItemController(dbContext context)
        {
            _context = context;
        }

        // GET: Item
        public async Task<IActionResult> Index()
        {
            return View(await _context.Item.Include("Person").ToListAsync());
        }

        public async Task<IActionResult> SelectOwner(string Description, string SerialNumber, string NameFilter, string SurnameFilter)
        {
            ViewBag.Description = Description;
            ViewBag.SerialNumber = SerialNumber;
            ViewBag.NameFilter = NameFilter;
            ViewBag.SurnameFilter = SurnameFilter;

            IQueryable<Person> unfiltered_users = _context.Person;

            if (!String.IsNullOrEmpty(NameFilter))
            {
                unfiltered_users = unfiltered_users.Where(u => u.Name.Contains(NameFilter));
            }
            if (!String.IsNullOrEmpty(SurnameFilter))
            {
                unfiltered_users = unfiltered_users.Where(u => u.Surname.Contains(SurnameFilter));
            }
            unfiltered_users = unfiltered_users.OrderBy(m => m.Surname);

            var users = await unfiltered_users.ToListAsync();

            return View(users);

        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> AddItemWithPerson(string Description, string SerialNumber, int PersonID)
        {
            Item item = new Item
            {
                SerialNumber = SerialNumber,
                Description = Description
            };

            var person = _context.Person.Where(p => p.ID == PersonID).FirstAsync();
            
            if (person.Result == null)
                return RedirectToAction(nameof(Index));

            item.Person = person.Result;
            _context.Add(item);
            await _context.SaveChangesAsync();

            return RedirectToAction(nameof(Index));
        }
        
        public async Task<IActionResult> RepairList(int? itemID)
        {
            if (itemID == null)
            {
                return NotFound();
            }

            var item = await _context.Item
            .Include(i => i.Repair)
            .FirstOrDefaultAsync(it => it.ID == itemID);

            var repairs  = new List<Repair>();
            foreach(var repair in item.Repair)
            {
                var tmpService =  await _context.Repair.Include(r => r.PickupCode).Include(r => r.RepairStatus).FirstOrDefaultAsync(r => r.ID == repair.ID);
                repairs.Add(tmpService);
            }

            return View(repairs);
        }
        public IActionResult AddNewPerson(string Description, string SerialNumber)
        {
            ViewBag.Description = Description;
            ViewBag.SerialNumber = SerialNumber;
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> AddNewPerson(string Description,string SerialNumber,[Bind("ID,Role,Name,Surname,Address,Email,PhoneNumber")] Person person)
        {
            Item item = new Item();

            item.SerialNumber=SerialNumber;
            item.Description = Description;

            if (ModelState.IsValid)
            {
                _context.Add(person);
                await _context.SaveChangesAsync();
            }

            item.Person = person;
            _context.Add(item);
            await _context.SaveChangesAsync();

            return RedirectToAction(nameof(Index));
        }

        // GET: Item/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var item = await _context.Item
                .FirstOrDefaultAsync(m => m.ID == id);
            if (item == null)
            {
                return NotFound();
            }

            return View(item);
        }

        // GET: Item/Create
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("ID,SerialNumber,Description")] Item item)
        {
            if (ModelState.IsValid)
            {
                _context.Add(item);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(item);
        }

        // GET: Item/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var item = await _context.Item.FindAsync(id);
            if (item == null)
            {
                return NotFound();
            }
            return View(item);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("ID,SerialNumber,Description")] Item item)
        {
            if (id != item.ID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(item);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ItemExists(item.ID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(item);
        }

        // GET: Item/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var item = await _context.Item
                .FirstOrDefaultAsync(m => m.ID == id);
            if (item == null)
            {
                return NotFound();
            }

            return View(item);
        }

        // POST: Item/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var item = await _context.Item.FindAsync(id);
            _context.Repair.RemoveRange(_context.Repair.Where(x => x.Item == item));
            _context.Item.Remove(item);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool ItemExists(int id)
        {
            return _context.Item.Any(e => e.ID == id);
        }
    }
}

Controllers/ServiceController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using TabApp.Models;

namespace TabApp.Controllers
{
    [Authorize]
    public class ServiceController : Controller
    {
        private readonly dbContext _context;

        public ServiceController(dbContext context)
        {
            _context = context;
        }

        // GET: Service
        public async Task<IActionResult> Index(int? repairID)
        {
            if (repairID == null)
            {
                return NotFound();
            }
            
            var repair = await _context.Repair
            .Include(r => r.Service)
            .Include(r => r.PickupCode)
            .FirstOrDefaultAsync(m => m.ID == repairID);       

            var services  = new List<Service>();
            foreach(var service in repair.Service)
            {
                var tmpService =  await _context.Service.Include(s => s.PriceList).FirstOrDefaultAsync(s => s.ID == service.ID);  
                services.Add(tmpService);
            }
            ViewBag.PickupCode = repair.PickupCode.Value;
            ViewBag.RepairID = repairID;
            return View(services);
        }

        // GET: Service/Details/5
        public async Task<IActionResult> Details(int? id, int? repairID)
        {
            if (id == null || repairID == null)
            {
                return NotFound();
            }

            var service = await _context.Service
                .Include(s => s.PriceList)
                .FirstOrDefaultAsync(m => m.ID == id);
            if (service == null)
            {
                return NotFound();
            }
            ViewBag.RepairID = repairID;
            return View(service);
        }

         public async Task<IActionResult> Preview()
        {
            return View(await _context.Service.ToListAsync());
        }

        // GET: Service/Create
        public async Task<IActionResult> Create(int? repairID)
        {
            if(repairID == null)
            {
                return NotFound();
            }

            var repair = await _context.Repair.FindAsync(repairID);
            if (repair == null)
            {
                    return NotFound();
            }
            
            ViewBag.RepairID = repairID;
            ViewData["PriceList"] = new SelectList(_context.PriceList, "ID", "Description");
            return View();
        }

        // POST: Service/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(int repairID, int priceListID, [Bind("ID,WarrantyDate,PartsCost")] Service service)
        {
            if (ModelState.IsValid)
            {
                var repair = await _context.Repair.FindAsync(repairID);
                service.Repair = repair;

                var priceList = await _context.PriceList.FindAsync(priceListID);
                service.PriceList = priceList;

                service.Person = await _context.Person.Include("LoginCredentials").Where(u => u.LoginCredentials.UserName == User.Identity.Name).FirstAsync();

                _context.Add(service);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index), new { repairID });
            }
            ViewData["PriceList"] = new SelectList(_context.PriceList, "ID", "Description");
            return View(service);
        }

        // GET: Service/Edit/5
        public async Task<IActionResult> Edit(int? id, int? repairID)
        {
            if (id == null || repairID == null)
            {
                return NotFound();
            }

            var service = await _context.Service.FindAsync(id);
            if (service == null)
            {
                return NotFound();
            }
            
            ViewBag.RepairID = repairID;
            return View(service);
        }

        // POST: Service/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, int repairID, [Bind("ID,WarrantyDate")] Service service)
        {
            if (id != service.ID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(service);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ServiceExists(service.ID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index), new { repairID });
            }
            return View(service);
        }

        // GET: Service/Delete/5
        public async Task<IActionResult> Delete(int? id, int? repairID)
        {
            if (id == null || repairID == null)
            {
                return NotFound();
            }

            var service = await _context.Service
                .FirstOrDefaultAsync(m => m.ID == id);
            if (service == null)
            {
                return NotFound();
            }

            ViewBag.RepairID = repairID;
            return View(service);
        }

        // POST: Service/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id, int repairID)
        {
            var service = await _context.Service.FindAsync(id);
            _context.Service.Remove(service);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index), new { repairID } );
        }

        private bool ServiceExists(int id)
        {
            return _context.Service.Any(e => e.ID == id);
        }
    }
}

Views/Repair/Add.cshtml
@model TabApp.Models.Repair

@{
    ViewData["Title"] = "New Repair";
}

<div class="container-fluid">
	<div class="row">
		<div class="col-md-12">
			<h3 class="text-center">
				Choose:
			</h3>
		</div>
	</div>
	<div class="row">
		<div class="col-md-6">
			 
			<button type="button" class="btn btn-success btn-block btn-lg">
                <a class="nav-link text-dark" asp-area="" asp-controller="Item" asp-action="Index">Add repair to existing item</a>				
			</button>
		</div>
		<div class="col-md-6">
			 
			<button type="button" class="btn btn-success btn-lg btn-block">
				<a class="nav-link text-dark" asp-area="" asp-controller="Item" asp-action="Create">Add repair to new item</a>	
			</button>
		</div>
	</div>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Repair/Create.cshtml
@model TabApp.Models.Repair

@{
    ViewData["Title"] = "Create";
}
<script>
    
    function myF(){
        if(@ViewBag.ItemID)
        {
            document.getElementById('itemID').value = '@ViewBag.ItemID';
            document.getElementById('ItemSerialNumber').value = '@ViewBag.ItemSerialNumber';
            document.getElementById('ItemDescription').value = '@ViewBag.ItemDescription';
            document.getElementById('ItemSerialNumber').setAttribute("readonly", true);
            document.getElementById('ItemDescription').setAttribute("readonly", true);
        }
       
    }
    
     window.onload = myF;
</script>

<h1>Create</h1>

<h4>Repair</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="All" class="text-danger"></div>
            <input type="hidden" id="itemID" name="itemID"/>
            <div class="form-group">
                <label asp-for="Item.SerialNumber" class="control-label">Item Serial Number</label>
                <input asp-for="Item.SerialNumber" class="form-control"  id="ItemSerialNumber"/>
                <span asp-validation-for="Item.SerialNumber" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Item.Description" class="control-label">Item Description</label>
                <input asp-for="Item.Description" class="form-control" id="ItemDescription"/>
                <span asp-validation-for="Item.Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="AdmissionDate" class="control-label"></label>
                <input asp-for="AdmissionDate" class="form-control" />
                <span asp-validation-for="AdmissionDate" class="text-danger"></span>
            </div>
            <div class="form-group form-check">
                <label class="form-check-label">
                    <input class="form-check-input" asp-for="Warranty" /> @Html.DisplayNameFor(model => model.Warranty)
                </label>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>


<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Repair/Delete.cshtml
@model TabApp.Models.Repair

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Repair</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.AdmissionDate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.AdmissionDate)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.IssueDate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.IssueDate)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Cost)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Cost)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Warranty)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Warranty)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.RepairStatus)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.RepairStatus)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.PickupCode)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.PickupCode)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Item)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Item.Description)
        </dd class>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="ID" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

Views/Repair/Details.cshtml
@model TabApp.Models.Repair

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Repair</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.AdmissionDate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.AdmissionDate)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.IssueDate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.IssueDate)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Cost)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Cost)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Warranty)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Warranty)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.RepairStatus)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.RepairStatus.Status)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.PickupCode)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.PickupCode.Value)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Item)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Item.Description)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.ID">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

Views/Repair/Edit.cshtml
@model TabApp.Models.Repair

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Repair</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="ID" />
            <div class="form-group">
                <label asp-for="AdmissionDate" class="control-label"></label>
                <input asp-for="AdmissionDate" class="form-control" />
                <span asp-validation-for="AdmissionDate" class="text-danger"></span>
            </div>
            <div class="form-group form-check">
                <label class="form-check-label">
                    <input class="form-check-input" asp-for="Warranty" /> @Html.DisplayNameFor(model => model.Warranty)
                </label>
            </div>
            <div class="form-group">
                <label> Select repair status</label>
                <select id="repairStatusID" name="repairStatusID" class="form-control" asp-items="ViewBag.RepairStatus"></select>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Repair/Index.cshtml
@model IEnumerable<TabApp.Models.Repair>

@{
    ViewData["Title"] = "Index";
}

<h2>Repairs</h2>

<p>
    <a asp-action="Add" class="btn btn-outline-primary">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.AdmissionDate)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.IssueDate)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Cost)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Warranty)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.RepairStatus)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.PickupCode)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Item)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.AdmissionDate)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.IssueDate)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Cost)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Warranty)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.RepairStatus.Status)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.PickupCode.Value)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Item.Description)
            </td>
            <td>
                <a asp-controller="Service" asp-action="Index" asp-route-repairID="@item.ID">Show services</a> | 
                <a asp-controller="Invoice" asp-action="Create" asp-route-repairID="@item.ID">Create Invoice</a> | 
                <a asp-action="Edit" asp-route-id="@item.ID">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.ID">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.ID">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>